import { callPostWebService, callGetWebService, callPutWebService } from '../../common/helpers/helpers';
import { startSpinner } from '../../common/loading/spinnerAction';
//grabs url and other data from config file.
//const CONFIG_FILE = require('../../../resources/stubs/config.json');
const CONFIG_FILE = require('../../../resources/stubs/config.json');
const env = require('../../../settings/env.js');
const path = env.PATH;
const giftRegistryURL = path+'giftRegistryURL.json';


//sets url to be used for api call
//const URL = CONFIG_FILE.config.giftRegistryURL+'?regID=216';
const URL = CONFIG_FILE.giftRegistryURL+'?regID=216';

export function saleitemGiftRegistryUpdate(item,transactionId,gift,modify_type){
    
    const params = {

        "SourceLoc":"NM-DIRECT",
	 "SourceLoc":"NM-DIRECT",
	 "Store":"0010",
	 "Terminal":"0216",
	 "StoreAssoc":"209289",
	 "ClientID":"0010:0216:06082018:033639",
	 "TransactionId":transactionId,
	"LineNumber": modify_type=='item'?item.lineNumber:undefined,
	"SKU": modify_type=='item'?item.itemNumber:undefined,
	"TransModify": modify_type=='item'?"N":"Y",
	"GiftRegistryNum": gift
    };
    const request = env.ENV_MODE=='dev1'?callPutWebService(URL, params):callGetWebService(giftRegistryURL, {});
    
    console.log("saleitemGiftRegistryUpdate Parameters being sent", params);
    
    return (dispatch) => {
         request.then(({data}) => {
             console.log(data);

            if(data.response_text == "GREC_SUCCESS") {
                dispatch({
                    type: 'GIFTRECEIPTUPDATE_REQUEST',
                    payload: data
                });
            }
            else {
                console.log('gift reducer action triggered');
                dispatch( {
                    
                    type: 'GIFTREGISTRYUPDATE_REQUEST',
                    payload: data
                    /*{  
                        "response_code":0,
                        "response_text":"AC_SUCCESS",
                        "transactionId":"1303",
                        "cartItems":{  
                           "items":[  
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"1",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"2",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"3",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"4",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"5",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"6",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"7",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"8",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"9",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"10",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"11",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"12",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"13",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"14",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"15",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"16",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"17",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"18",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"19",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"20",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"21",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"00000000003F",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"22",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"00003F022020",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000\u0000",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"23",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"022020202020",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000\u0000\u0000\u0000?",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"24",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"202020205049",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000\u0000\u0000",
                                 "size":"\u0000?\u0002  ",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"25",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"2050494E4543",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000\u0000\u0000",
                                 "color":"\u0000?\u0002",
                                 "size":"     ",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"26",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"4E45434F4E4F",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000\u0000\u0000\u0000?\u0002",
                                 "color":"   ",
                                 "size":"   PI",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"8224",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"27",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"4F4E4F204E4F",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"\u0000?\u0002   ",
                                 "color":"   ",
                                 "size":"PINEC",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"8224",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"28",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"204E4F205349",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"      ",
                                 "color":"PIN",
                                 "size":"ECONO",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"29281",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"29",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"205349000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"   PIN",
                                 "color":"ECO",
                                 "size":"NO NO",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"002022",
                                 "class":"000708",
                                 "subClass":"8224",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"30",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"000000000000",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              },
                              {  
                                 "itemNumber":"0000000000000043",
                                 "pim_SKU_ID":"0000401023029077",
                                 "itemDesc":"Xmas Decor                              ",
                                 "style":"PINECONE GLD",
                                 "color":"NO COLOR",
                                 "size":"NO SIZE",
                                 "taxCode":"\u0000",
                                 "itemPrice":7.5,
                                 "salePrice":7.5,
                                 "taxPercent":10.5,
                                 "quantity":1,
                                 "itemsPrice":7.5,
                                 "totalPrice":8.29,
                                 "itemsTax":0.79,
                                 "itemTax":0.79,
                                 "department":"2022",
                                 "class":"708",
                                 "subClass":"0",
                                 "itemType":"",
                                 "priceType":"",
                                 "currencyCode":"",
                                 "unitOfMeasure":"",
                                 "imgLink":"",
                                 "presaleFlag":false,
                                 "lineNumber":"31",
                                 "itemStatus":"1",
                                 "flag_1":0,
                                 "eventNumber":"",
                                 "eventDescription":"",
                                 "replenishQty":0,
                                 "replenishDays":0,
                                 "gift_reg":"0",
                                 "discounts":[  
                     
                                 ],
                                 "comment":[  
                     
                                 ]
                              }
                           ],
                           "associateDiscount":null,
                           "totalTax":24.49,
                           "subTotal":232.5,
                           "total":256.99
                        },
                        "totalTax":24.49,
                        "subTotal":232.5,
                        "total":256.99
                     }*/
                    
                });
            }

           
        }).catch((err) => {
            dispatch(startSpinner(false));
            dispatch({
                    type: 'GIFTREGISTRYUPDATE_FAIL',
                });
            // console.log("ERROR",err);
            // alert("ERROR");
        }); 
        
    };
}