export const REMINDERS_SUCCESS ='REMINDERS_SUCCESS';
export const IM_SUCCESS = 'IM_SUCCESS';
export const IM_INVALIDREQUEST ='IM_INVALIDREQUEST';
export const REMINDERS_INVALID ='REMINDERS_INVALID';
export const IM_GENERALERROR ='IM_GENERALERROR';
export const REMINDERS_GENERAL = 'REMINDERS_GENERAL';
export const REMINDERS_REQUEST_VALIDFAILED = 'REMINDERS_REQUEST_VALIDFAILED';
export const IM_NOREMINDER = "IM_NOREMINDER";