export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SEND_USERPIN = 'SEND_USERPIN';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CLEAR_REQUEST = 'CLEAR_REQUEST';

// INCIRCLE
export const CUST_INCIRCLE_INFO_REQUEST = 'CUST_INCIRCLE_INFO_REQUEST';
export const INCIRCLE_GIFT_CARDS = 'INCIRCLE_GIFT_CARDS';

//Transaction_ID
export const TRANSACTION_ID_REQUEST = 'TRANSACTION_ID_REQUEST';

export const START_SPINNER = 'START_SPINNER';

//Payment
// Add Item To Cart
export const GET_CLIENT_DETAILS = 'GET_CLIENT_DETAILS';
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const UPDATE_CLIENT_DETAILS = 'UPDATE_CLIENT_DETAILS';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export const TRANS_DISCOUNT_APPLIED = 'TRANS_DISCOUNT_APPLIED';
export const IM_RINGINGASSOCIATE = 'IM_RINGINGASSOCIATE';
export const TRANS_DISCOUNT_FAIL = 'TRANS_DISCOUNT_FAIL';
export const ASSOCIATE_DISCOUNT_APPLIED= 'ASSOCIATE_DISCOUNT_APPLIED';
export const ASSOCIATE_DISCOUNT_FAIL = 'ASSOCIATE_DISCOUNT_FAIL';
export const NAV_TO_SEND = 'NAV_TO_SEND';

//csr Details
export const GET_CSR_HISTORY = 'GET_CSR_HISTORY';
// Customer Search
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const SET_CUSTOMER = 'SET_CUSTOMER';


//Product Search
export const PRODUCT_SEARCH_KEYWORD_SUCCESS = 'PRODUCT_SEARCH_KEYWORD_SUCCESS';
export const PRODUCT_SEARCH_KEYWORD_FAIL = 'PRODUCT_SEARCH_KEYWORD_FAIL';
export const PRODUCT_SEARCH_PIMSKU_SUCCESS = 'PRODUCT_SEARCH_PIMSKU_SUCCESS';
export const PRODUCT_SEARCH_PIMSKU_FAIL = 'PRODUCT_SEARCH_PIMSKU_FAIL';
export const PRODUCT_SEARCH_UPC_SUCCESS = 'PRODUCT_SEARCH_UPC_SUCCESS';
export const PRODUCT_SEARCH_UPC_FAIL = 'PRODUCT_SEARCH_UPC_FAIL';
export const PRODUCT_SEARCH_STYLE_SUCCESS = 'PRODUCT_SEARCH_STYLE_SUCCESS';
export const PRODUCT_SEARCH_STYLE_FAIL = 'PRODUCT_SEARCH_STYLE_FAIL';
export const PRODUCT_SEARCH_CATALOG_ITEM_SUCCESS = 'PRODUCT_SEARCH_CATALOG_ITEM_SUCCESS';
export const PRODUCT_SEARCH_CATALOG_ITEM_FAIL = 'PRODUCT_SEARCH_CATALOG_ITEM_FAIL';
export const PRODUCT_FILTER_SEARCH_ITEM_SUCCESS = 'PRODUCT_FILTER_SEARCH_ITEM_SUCCESS';
export const PRODUCT_FILTER_SEARCH_ITEM_FAIL = 'PRODUCT_FILTER_SEARCH_ITEM_FAIL';
export const PRODUCT_DETAIL_INFO_ITEM_SUCCESS = 'PRODUCT_DETAIL_INFO_ITEM_SUCCESS';
export const PRODUCT_DETAIL_INFO_ITEM_FAIL = 'PRODUCT_DETAIL_INFO_ITEM_FAIL';


//SALE SERVICES AND MODIFICATION
export const GET_GIFT_WRAP = 'GET_GIFT_WRAP';
export const CLEAR_GIFT_WRAP = 'CLEAR_GIFT_WRAP';
export const ADD_TO_GIFT_WRAP = 'ADD_TO_GIFT_WRAP';
export const ADD_ALTERATIONS = 'ADD_ALTERATIONS';
export const RESET_ALTERATION = 'RESET_ALTERATION';

//CartRendere
export const CHANGE_ITEM_SELECTED = 'CHANGE_ITEM_SELECTED';
export const CHANGE_ITEMS_SELECTED = 'CHANGE_ITEMS_SELECTED';
