export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SEND_USERPIN = 'SEND_USERPIN';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CLEAR_REQUEST = 'CLEAR_REQUEST';

// INCIRCLE
export const CUST_INCIRCLE_INFO_REQUEST = 'CUST_INCIRCLE_INFO_REQUEST';
export const INCIRCLE_GIFT_CARDS = 'INCIRCLE_GIFT_CARDS';

//Transaction_ID
export const TRANSACTION_ID_REQUEST = 'TRANSACTION_ID_REQUEST';

//SALUTATION
export const GET_SALUTATION = 'GET_SALUTATION';

export const START_SPINNER = 'START_SPINNER';


//Payment
// Add Item To Cart
export const GET_CLIENT_DETAILS = 'GET_CLIENT_DETAILS';
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST';
export const UPDATE_CLIENT_DETAILS = 'UPDATE_CLIENT_DETAILS';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export const TRANS_DISCOUNT_APPLIED = 'TRANS_DISCOUNT_APPLIED';
export const IM_RINGINGASSOCIATE = 'IM_RINGINGASSOCIATE';
export const IM_INVALIDASSOCIATE = 'IM_INVALIDASSOCIATE';
export const TRANS_DISCOUNT_FAIL = 'TRANS_DISCOUNT_FAIL';
export const ASSOCIATE_DISCOUNT_APPLIED= 'ASSOCIATE_DISCOUNT_APPLIED';
export const ASSOCIATE_DISCOUNT_ALREADY_APPLIED= 'ASSOCIATE_DISCOUNT_ALREADY_APPLIED';
export const TD_DISCOUNTEXCEEDS= 'TD_DISCOUNTEXCEEDS';
export const DEFAULT_SKU = 'DEFAULT_SKU';

export const ASSOCIATE_DISCOUNT_FAIL = 'ASSOCIATE_DISCOUNT_FAIL';

//Send
export const NAV_TO_SEND = 'NAV_TO_SEND';
export const SHIPMENT_OPTIONS_REQUEST = 'SHIPMENT_OPTIONS_REQUEST';
export const DIRECT_SEND_REQUEST = 'DIRECT_SEND_REQUEST';
export const FREQ_SHIPPED_ADDRESSES='FREQ_SHIPPED_ADDRESSES';
export const SHIPMENT_OPTIONS_REQUEST_FAILURE = 'SHIPMENT_OPTIONS_REQUEST_FAILURE';
export const DIRECT_SEND_REQUEST_FAILURE = 'DIRECT_SEND_REQUEST_FAILURE';
export const FREQ_SHIPPED_ADDRESSES_FAILURE ='FREQ_SHIPPED_ADDRESSES_FAILURE';
export const AUTH_CODE_REQUEST = 'AUTH_CODE_REQUEST';
export const AUTH_CODE_REQUEST_FAILURE = 'AUTH_CODE_REQUEST_FAILURE';
export const SEND_CLEAR_ERROR = 'SEND_CLEAR_ERROR';
export const SEND_CLEAR_RESPONSE = 'SEND_CLEAR_RESPONSE';
export const SELECT_STORE_SEND ='SELECT_STORE_SEND';
export const SHIPPING_OPTIONS_SEND ='SHIPPING_OPTIONS_SEND';
//csr Details
export const GET_CSR_HISTORY = 'GET_CSR_HISTORY';
// Customer Search
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const SET_CUSTOMER = 'SET_CUSTOMER';


//Product Search
export const PRODUCT_SEARCH_KEYWORD_SUCCESS = 'PRODUCT_SEARCH_KEYWORD_SUCCESS';
export const PRODUCT_SEARCH_KEYWORD_FAIL = 'PRODUCT_SEARCH_KEYWORD_FAIL';
export const PRODUCT_SEARCH_PIMSKU_SUCCESS = 'PRODUCT_SEARCH_PIMSKU_SUCCESS';
export const PRODUCT_SEARCH_PIMSKU_FAIL = 'PRODUCT_SEARCH_PIMSKU_FAIL';
export const PRODUCT_SEARCH_UPC_SUCCESS = 'PRODUCT_SEARCH_UPC_SUCCESS';
export const PRODUCT_SEARCH_UPC_FAIL = 'PRODUCT_SEARCH_UPC_FAIL';
export const PRODUCT_SEARCH_STYLE_SUCCESS = 'PRODUCT_SEARCH_STYLE_SUCCESS';
export const PRODUCT_SEARCH_STYLE_FAIL = 'PRODUCT_SEARCH_STYLE_FAIL';
export const PRODUCT_SEARCH_CATALOG_ITEM_SUCCESS = 'PRODUCT_SEARCH_CATALOG_ITEM_SUCCESS';
export const PRODUCT_SEARCH_CATALOG_ITEM_FAIL = 'PRODUCT_SEARCH_CATALOG_ITEM_FAIL';
export const PRODUCT_FILTER_SEARCH_ITEM_SUCCESS = 'PRODUCT_FILTER_SEARCH_ITEM_SUCCESS';
export const PRODUCT_FILTER_SEARCH_ITEM_FAIL = 'PRODUCT_FILTER_SEARCH_ITEM_FAIL';
export const PRODUCT_DETAIL_INFO_ITEM_SUCCESS = 'PRODUCT_DETAIL_INFO_ITEM_SUCCESS';
export const PRODUCT_DETAIL_INFO_ITEM_FAIL = 'PRODUCT_DETAIL_INFO_ITEM_FAIL';


//SALE SERVICES AND MODIFICATION
export const GET_GIFT_WRAP = 'GET_GIFT_WRAP';
export const CLEAR_GIFT_WRAP = 'CLEAR_GIFT_WRAP';
export const ADD_TO_GIFT_WRAP = 'ADD_TO_GIFT_WRAP';
export const ADD_ALTERATIONS = 'ADD_ALTERATIONS';
export const RESET_ALTERATION = 'RESET_ALTERATION';
export const GP_PRICENOTFOUND = 'GP_PRICENOTFOUND';

//CartRendere
export const CHANGE_ITEM_SELECTED = 'CHANGE_ITEM_SELECTED';
export const CHANGE_ITEMS_SELECTED = 'CHANGE_ITEMS_SELECTED';
export const NON_SKU_SELECTED = 'NON_SKU_SELECTED';

// Send Modals
export const UPDATE_CLIENTELE_EMAIL = 'UPDATE_CLIENTELE_EMAIL';
export const UPDATE_NON_CLIENTELE_INFO = 'UPDATE_NON_CLIENTELE_INFO';
export const UPDATE_TRACKING_CLIENTELE = 'UPDATE_TRACKING_CLIENTELE';
export const UPDATE_TRACKING_NON_CLIENTELE = 'UPDATE_TRACKING_NON_CLIENTELE';

//OPTION SEVEN
export const OPTION_SEVEN_SEND = 'OPTION_SEVEN_SEND';

//GIFT CARD
export const ADD_GIFTCARD_SUCCESS = 'ADD_GIFTCARD_SUCCESS';
export const ADD_GIFTCARD_FAILURE = 'ADD_GIFTCARD_FAILURE';
export const VALIDATE_DL_SUCCESS = 'VALIDATE_DL_SUCCESS';
export const VALIDATE_DL_FAILURE = 'VALIDATE_DL_FAILURE';

//ICC GIFT CARD
export const GET_GIFTCARD_FAILURE = 'GET_GIFTCARD_FAILURE';
export const GET_GIFTCARD_SUCCESS = 'GET_GIFTCARD_SUCCESS';
export const GET_GIFTCARD_FORBIDDEN_ERROR = ' GET_GIFTCARD_FORBIDDEN_ERROR';
export const GIFTCARD_CLASS_SUCCESS = 'GIFTCARD_CLASS_SUCCESS';
export const GIFTCARD_CLASS_FAILURE = 'GIFTCARD_CLASS_FAILURE';
export const CONVERT_SALT_SUCCESS = 'CONVERT_SALT_SUCCESS';
export const CONVERT_SALT_FAILURE = 'CONVERT_SALT_FAILURE';
export const GIFTCARD_SALT_SUCCESS = 'GIFTCARD_SALT_SUCCESS';
export const GIFTCARD_SALT_FAILURE = 'GIFTCARD_SALT_FAILURE';
export const UPDATE_RELOAD_SUCCESS = 'UPDATE_RELOAD_SUCCESS';
export const UPDATE_RELOAD_FAILURE = 'UPDATE_RELOAD_FAILURE';
export const FINCEN_SUCCESS = 'FINCEN_SUCCESS';
export const FINCEN_FAILURE = 'FINCEN_FAILURE';

//POST VOID
export const RENDER_POST_VOID_CART = 'RENDER_POST_VOID_CART'